apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-app-config
  namespace: default
data:
  NODE_ENV: "production"
  WEB_SERVER_PORT: "3000"
  WEB_SOCKETS_SERVER_PORT: "3001"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "chatapp"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  WEB_SERVER_URL: "http://web-server-service:3000"
  SOCKET_SERVER_URL: "http://socket-server-service:3001"