apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-web-sockets-server
  namespace: default
  labels:
    app: chat-app-web-sockets-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-app-web-sockets-server
  template:
    metadata:
      labels:
        app: chat-app-web-sockets-server
    spec:
      containers:
      - name: chat-app-web-sockets-server
        image: chat-app-web-sockets-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: chat-app-config
        - secretRef:
            name: chat-app-secrets
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-web-sockets-server-service
  namespace: default
spec:
  selector:
    app: chat-app-web-sockets-server
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP